# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  #Setting Vagrant virtual box image to be used
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  
#Display GUI of Virtual Machine
  config.vm.provider "virtualbox" do |vb|
	vb.gui = true
	vb.name = "JavaMOP"
  end
  
#Run provisioning script
	 config.vm.provision :shell, privileged: false, path: "install.sh" 
end
