# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.provider "virtualbox" do |vb|
	vb.gui = true
	vb.name = "JavaMOP"
  end
	 config.vm.provision :shell, privileged: false, path: "install.sh" 
end
